export default function SanctionPreview() {
  return (
    <div className="mt-6 text-sm text-white/60 border border-white/10 rounded-lg p-4 bg-white/5">
      <p className="mb-2 font-medium text-white">
        Sanction Letter Notice
      </p>
      <p>
        This sanction letter is generated by ALIS based on provided information
        and verification checks. It is intended for demonstration and guidance
        purposes only and is not legally binding.
      </p>
    </div>
  );
}
